from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest


@pytest.fixture(scope="session")
def artifact_dir() -> Path:
    path = Path("test_outputs").resolve()
    path.mkdir(parents=True, exist_ok=True)
    readme = path / "README.md"
    readme.write_text(
        "# qREST Agent Test Outputs\n\n"
        "This directory is generated by pytest and is ignored by git. "
        "It stores representative metadata, audit, tool, and validation outputs for manual review.\n",
        encoding="utf-8",
    )
    return path


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
